language: go

go:
  - 1.11.x
  - 1.12.x

before_install:
  - go get github.com/mattn/goveralls

env:
  - GO111MODULE=on GOPROXY=https://proxy.golang.org

script:
  - make
#  - make testflags="-race"
  # submit to goveralls only on the latest version to avoid timeouts
  - if [[ $TRAVIS_GO_VERSION == 1.12* ]]; then $GOPATH/bin/goveralls -service=travis-ci; fi
