[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/fortytw2/leaktest"
  version = "1.3.0"

[[constraint]]
  name = "github.com/InVisionApp/go-logger"
  version = "1.0.1"

[[constraint]]
  name = "go.opencensus.io"
  version = "0.19.0"
